image: debian:latest

before_script:
    - apt-get update
    - apt-get -y install php5 php5-cli php5-gd git curl php5-curl php5-sqlite php5-xdebug
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin
    - /usr/bin/composer.phar install

job_test:
    stage: test
    script: "./vendor/bin/phpunit --coverage-text"